{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 74,
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from vincenty import vincenty\n",
    "import datetime\n",
    "import collections\n",
    "import math\n",
    "\n",
    "\n",
    "def show_unique(series):\n",
    "    '''\n",
    "    Return a list of the unique elements in a pandas series\n",
    "    '''\n",
    "    \n",
    "    all_elements = list(series)\n",
    "    seen = set()\n",
    "    seen_add = seen.add\n",
    "    unique_elements = [x for x in all_elements if not (x in seen or seen_add(x))]\n",
    "\n",
    "    return unique_elements\n",
    "\n",
    "def remove_subspp(string):\n",
    "    '''\n",
    "    Common names sometimes have a parenthetical comment\n",
    "    about supspecific designation at the end of the \n",
    "    species name. Returns the first part of the name\n",
    "    before the open parenthesis (with ' ' stripped off)\n",
    "    '''\n",
    "    return string.split('(')[0].strip()\n",
    "\n",
    "\n",
    "def identify_centers(df, radius_miles = 5):\n",
    "    '''\n",
    "    Create a dictionary where the\n",
    "    keys = centers and the values = list of points\n",
    "    within the desired radius\n",
    "    '''\n",
    "    \n",
    "    # Create a list of all unique points to use for our centers\n",
    "    all_points = show_unique(df['Location'])\n",
    "    centers = all_points #TODO: create a more efficient center-finding algo\n",
    "\n",
    "    my_dict = {}\n",
    "    centers = all_points\n",
    "    for center in centers:\n",
    "        close_points = []\n",
    "        for point in all_points:\n",
    "            distance = vincenty(center, point, miles=True)\n",
    "            if distance < radius_miles:\n",
    "                close_points.append(point)\n",
    "\n",
    "        my_dict[center] = close_points\n",
    "        \n",
    "    return my_dict\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def interval_without_year(date1, date2):\n",
    "    '''\n",
    "    Return number of days between two dates\n",
    "    \n",
    "    Returns interval of days between two dates regardless of year. \n",
    "    For instance, January 1, 2019 and January 4, 1999 are considered \n",
    "    3 days apart with this method, no matter which one is provided\n",
    "    as day1 or day2.\n",
    "    \n",
    "    This function may be imperfect WRT leap years.\n",
    "    \n",
    "    Inputs:\n",
    "        date1, date2: datetime.date objects\n",
    "        \n",
    "    Returns:\n",
    "        number of days between them on calendar (regardless of year)\n",
    "    \n",
    "    '''\n",
    "    \n",
    "    delta = date1-date2\n",
    "    way1 = delta.days % 365\n",
    "    way2 = 365-way1\n",
    "    \n",
    "    if way1 < way2: return way1\n",
    "    else: return way2\n",
    "\n",
    "\n",
    "    \n",
    "def select_loc_df(df, my_dict, center): \n",
    "    '''\n",
    "    Select relevant sightings by location\n",
    "    \n",
    "    For a single center (key), return a DF with only:\n",
    "    - sightings from locations in the desired radius (value) \n",
    "    - sightings from a desired date range\n",
    "    \n",
    "    Inputs:\n",
    "        df: the full dataframe to select sightings from\n",
    "        my_dict: the dictionary associating centers with lists\n",
    "            of points within the radius\n",
    "        center: the specific dictionary key to use\n",
    "    \n",
    "    '''\n",
    "\n",
    "    # Select only locations corresponding to radius around the center\n",
    "    return df[df['Location'].isin(my_dict[center])]\n",
    "\n",
    "\n",
    "\n",
    "def select_date_df(df, month, day, interval=4): \n",
    "    '''\n",
    "    Select relevant sightings by date\n",
    "    \n",
    "    For a single center (key), return a DF with only sightings from a desired date range\n",
    "    \n",
    "    Inputs:\n",
    "        df: the full dataframe to select sightings from\n",
    "        month, day: the date to center a date range around\n",
    "        interval: the number of days before & after the specified\n",
    "            date to include sightings from\n",
    "    \n",
    "    '''\n",
    "    \n",
    "    # Select only locations within date range\n",
    "    desired_date=datetime.date(2019, month, day) #2019 is a placeholder year\n",
    "    df['Interval'] = df['Date'].apply(interval_without_year, date2=desired_date)\n",
    "    selected_sightings = df.loc[df['Interval'] <= interval]\n",
    "    \n",
    "     \n",
    "    return selected_sightings\n",
    "\n",
    "    \n",
    "    \n",
    "def calculate_score(df):\n",
    "\n",
    "    '''\n",
    "    Calculate score of DF\n",
    "    \n",
    "    Calculate the score of a DF by finding\n",
    "    the number of checklists on which a species was reported.\n",
    "    This could be modified to be more sophisticated in the future.\n",
    "    \n",
    "    Inputs:\n",
    "        df: a dataframe with a column 'Common Name'\n",
    "    \n",
    "    Outputs:\n",
    "        the sum of the number of checklists each species\n",
    "        appeared on--which is identical to df.shape[0]\n",
    "    '''\n",
    "    \n",
    "    \n",
    "    collapsed_df = df['Common Name'].value_counts()\n",
    "    \n",
    "    return sum(collapsed_df), collapsed_df\n",
    "\n",
    "    \n",
    "    \n",
    "def import_data(data_filename, lifelist_filename, month, day, radius_miles):\n",
    "\n",
    "    '''\n",
    "    \n",
    "    Superfunction to import and select relevant data\n",
    "    \n",
    "    Returns:\n",
    "        A dictionary where the keys are centers, and the\n",
    "        values are dataframes. Each dataframe contains\n",
    "        sightings of lifer birds from the desired day \n",
    "        range within the radius of the key\n",
    "    '''\n",
    "    \n",
    "    # Import data\n",
    "    rough_df = pd.DataFrame.from_csv(data_filename, index_col=None)\n",
    "\n",
    "    # Add location column\n",
    "    rough_df['Location'] = rough_df.apply(lambda row: (row['Latitude'], row['Longitude']), axis=1)\n",
    "    \n",
    "    # Remove \"sp.,\" slashes, and hybrids through a several-step process:\n",
    "    rough_df = rough_df.loc[\n",
    "        ~(\n",
    "            rough_df['Scientific Name'].str.contains('\\.')\n",
    "        ) &\n",
    "        ~(\n",
    "            (\n",
    "                rough_df['Scientific Name'].str.contains('/')\n",
    "            ) & \n",
    "            (\n",
    "                ~rough_df['Common Name'].str.contains('\\(') \n",
    "                # Required because some subspecific designations (i.e. those with\n",
    "                # parentheses in the common name) have slashes in the scientific name\n",
    "                # (and in the common name!)\n",
    "                # This isn't perfect because of Traill's and Western species groups\n",
    "                # (and potentially some others), which is taken care of later.\n",
    "            )\n",
    "        ) &\n",
    "        ~(\n",
    "            rough_df['Common Name'].str.contains('hybrid')\n",
    "        )\n",
    "    ]\n",
    "    # Remove subspecific designations\n",
    "    rough_df['Common Name'] = rough_df['Common Name'].apply(remove_subspp)\n",
    "    # Remove those pesky species slashes like Pac-Slope/Cordy (Western)\n",
    "    rough_df = rough_df.loc[~rough_df['Common Name'].str.contains('/')]\n",
    "\n",
    "    # Select the necessary columns\n",
    "    fine_df = rough_df[['Submission ID', 'Common Name', 'Count', 'Location', 'Date']]\n",
    "    \n",
    "    # Replace Xs with NaNs\n",
    "    fine_df.reset_index(drop=True, inplace=True) # Drop current index (don't incorporate into DF)\n",
    "    df = fine_df.replace(to_replace='X', value=1)\n",
    "    df['Count'] = pd.to_numeric(df['Count']) #Coerce 1s from strs to numeric\n",
    "    df['Date'] = pd.to_datetime(df['Date']).dt.date # Convert to datetime.date\n",
    "    \n",
    "    # Generate list of lifers from .csv file\n",
    "    life_list = []\n",
    "    with open(lifelist_filename) as f:\n",
    "        reader = csv.reader(f)\n",
    "        for line in reader:\n",
    "            life_list.append(line[0].lower()) \n",
    "\n",
    "    # Remove species that are already on one's life list\n",
    "    df = df[~df['Common Name'].str.lower().isin(life_list)]\n",
    "    \n",
    "    \n",
    "    # Remove checklists from outside of this date range\n",
    "    df = select_date_df(df, month, day, interval=4)\n",
    "    \n",
    "    \n",
    "    # Identify a dict of centers\n",
    "    my_dict = identify_centers(df, radius_miles)\n",
    "    \n",
    "    \n",
    "    # For each center, generate a relevant DF and calculate its score\n",
    "    all_dfs = {}\n",
    "    all_scores = {}\n",
    "    for center in my_dict.keys():\n",
    "        \n",
    "        # Select only locations within radius\n",
    "        selected_df = select_loc_df(df, my_dict, center)\n",
    "        \n",
    "        # Calculate score\n",
    "        score, collapsed_df = calculate_score(selected_df)\n",
    "        \n",
    "        all_dfs[center] = collapsed_df\n",
    "        all_scores[center] = score\n",
    "        \n",
    "    \n",
    "    return all_dfs, all_scores\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def main(data_filename, lifelist_filename, month, day, num_spots, radius_miles):\n",
    "    '''\n",
    "    num_spots = number of top spots to show'''\n",
    "    \n",
    "    # Get dict of dfs of all lifer sightings\n",
    "    dfs, scores = import_data(data_filename, lifelist_filename, month, day, radius_miles)\n",
    "    \n",
    "    # Sort by scores\n",
    "    sorted_d = sorted(((value, key) for (key,value) in scores.items()), reverse=True)\n",
    "    \n",
    "    if len(sorted_d) < num_spots:\n",
    "        num_to_show = len(sorted_d)\n",
    "    else:\n",
    "        num_to_show = num_spots\n",
    "    \n",
    "    \n",
    "    for i in range(num_to_show):\n",
    "        center =  sorted_d[i][1]\n",
    "        \n",
    "        # Identify most common targets\n",
    "        center_df = dfs[center]\n",
    "        top_10percent = math.ceil(.1 * center_df.size)\n",
    "        targets = list(center_df.reset_index()['index'][0:top_10percent])\n",
    "        \n",
    "        print('Top spot {}:'.format(i+1), center)\n",
    "        print('Number possible targets:', sorted_d[i][0])\n",
    "        print('Most common targets:', targets)\n",
    "        print('')\n",
    "    \n",
    "    #return dfs, scores\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-1-acb59b1515fe>\", line 7, in <module>\n",
      "    data = list(reader)\n",
      "OSError: [Errno 5] Input/output error\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2910, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-1-acb59b1515fe>\", line 7, in <module>\n",
      "    data = list(reader)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 1828, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1090, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 311, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 345, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 1483, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 1441, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/anaconda3/lib/python3.6/posixpath.py\", line 374, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-1-acb59b1515fe>\", line 7, in <module>\n",
      "    data = list(reader)\n",
      "OSError: [Errno 5] Input/output error\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2910, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-1-acb59b1515fe>\", line 7, in <module>\n",
      "    data = list(reader)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 1828, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2850, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2927, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 1831, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1371, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1279, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)\n",
      "TypeError: must be str, not list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 1828, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1090, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 311, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 345, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 1483, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 1441, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/anaconda3/lib/python3.6/posixpath.py\", line 374, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-1-acb59b1515fe>\", line 7, in <module>\n",
      "    data = list(reader)\n",
      "OSError: [Errno 5] Input/output error\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2910, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-1-acb59b1515fe>\", line 7, in <module>\n",
      "    data = list(reader)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 1828, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2850, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2927, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 1831, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1371, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1279, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "    formatted_exceptions += self.prepare_chained_exception_message(evalue.__cause__)\n",
      "TypeError: must be str, not list\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 1828, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1090, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 311, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 345, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 1483, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 1441, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 725, in getmodule\n",
      "    file = getabsfile(object, _filename)\n",
      "  File \"/anaconda3/lib/python3.6/inspect.py\", line 709, in getabsfile\n",
      "    return os.path.normcase(os.path.abspath(_filename))\n",
      "  File \"/anaconda3/lib/python3.6/posixpath.py\", line 374, in abspath\n",
      "    cwd = os.getcwd()\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "must be str, not list",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   1827\u001b[0m                         \u001b[0;31m# in the engines. This should return a list of strings.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1828\u001b[0;31m                         \u001b[0mstb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_render_traceback_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1829\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'KeyboardInterrupt' object has no attribute '_render_traceback_'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mrun_code\u001b[0;34m(self, code_obj, result)\u001b[0m\n\u001b[1;32m   2925\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mresult\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2926\u001b[0m                 \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror_in_exec\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msys\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2927\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshowtraceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrunning_compiled_code\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2928\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2929\u001b[0m             \u001b[0moutflag\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\u001b[0m in \u001b[0;36mshowtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   1829\u001b[0m                     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1830\u001b[0m                         stb = self.InteractiveTB.structured_traceback(etype,\n\u001b[0;32m-> 1831\u001b[0;31m                                             value, tb, tb_offset=tb_offset)\n\u001b[0m\u001b[1;32m   1832\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1833\u001b[0m                     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_showtraceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mstb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1369\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1370\u001b[0m         return FormattedTB.structured_traceback(\n\u001b[0;32m-> 1371\u001b[0;31m             self, etype, value, tb, tb_offset, number_of_lines_of_context)\n\u001b[0m\u001b[1;32m   1372\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1373\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1277\u001b[0m             \u001b[0;31m# Verbose modes need a full traceback\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1278\u001b[0m             return VerboseTB.structured_traceback(\n\u001b[0;32m-> 1279\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb_offset\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mnumber_of_lines_of_context\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1280\u001b[0m             )\n\u001b[1;32m   1281\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/anaconda3/lib/python3.6/site-packages/IPython/core/ultratb.py\u001b[0m in \u001b[0;36mstructured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1138\u001b[0m             \u001b[0mexception\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_parts_of_chained_exception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1139\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mexception\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1140\u001b[0;31m                 \u001b[0mformatted_exceptions\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprepare_chained_exception_message\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mevalue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__cause__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1141\u001b[0m                 \u001b[0metype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mevalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0metb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mexception\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1142\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: must be str, not list"
     ]
    }
   ],
   "source": [
    "# Store data in file\n",
    "import csv\n",
    "\n",
    "ebird_data_file = '/Volumes/seagate-storage/ebird_data/ebd_relJan-2019.txt'\n",
    "with open(ebird_data_file, 'r') as f:\n",
    "    reader = csv.reader(f, delimiter=\"\\t\")\n",
    "    data = list(reader)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Top spot 1: (39.4029606, -94.5407438)\n",
      "Number possible targets: 305\n",
      "Most common targets: ['American Robin', 'American Crow', 'House Finch', 'Black-capped Chickadee', 'Mourning Dove', 'Northern Cardinal', 'House Sparrow']\n",
      "\n",
      "Top spot 2: (39.398638, -94.532882)\n",
      "Number possible targets: 305\n",
      "Most common targets: ['American Robin', 'American Crow', 'House Finch', 'Black-capped Chickadee', 'Mourning Dove', 'Northern Cardinal', 'House Sparrow']\n",
      "\n",
      "Top spot 3: (39.390881, -94.5545417)\n",
      "Number possible targets: 305\n",
      "Most common targets: ['American Robin', 'American Crow', 'House Finch', 'Black-capped Chickadee', 'Mourning Dove', 'Northern Cardinal', 'House Sparrow']\n",
      "\n",
      "Top spot 4: (39.311269, -94.564534)\n",
      "Number possible targets: 305\n",
      "Most common targets: ['American Robin', 'American Crow', 'House Finch', 'Black-capped Chickadee', 'Mourning Dove', 'Northern Cardinal', 'House Sparrow']\n",
      "\n",
      "Top spot 5: (39.251436, -94.441424)\n",
      "Number possible targets: 305\n",
      "Most common targets: ['American Robin', 'American Crow', 'House Finch', 'Black-capped Chickadee', 'Mourning Dove', 'Northern Cardinal', 'House Sparrow']\n",
      "\n",
      "Top spot 6: (39.25133710000001, -94.4367209)\n",
      "Number possible targets: 305\n",
      "Most common targets: ['American Robin', 'American Crow', 'House Finch', 'Black-capped Chickadee', 'Mourning Dove', 'Northern Cardinal', 'House Sparrow']\n",
      "\n",
      "Top spot 7: (39.249902299999995, -94.39508909999999)\n",
      "Number possible targets: 305\n",
      "Most common targets: ['American Robin', 'American Crow', 'House Finch', 'Black-capped Chickadee', 'Mourning Dove', 'Northern Cardinal', 'House Sparrow']\n",
      "\n",
      "Top spot 8: (26.071054500000002, -97.4693613)\n",
      "Number possible targets: 49\n",
      "Most common targets: ['Redhead', 'Brown Pelican', 'Snowy Egret', 'Willet']\n",
      "\n",
      "Top spot 9: (26.0780372, -97.16895509999999)\n",
      "Number possible targets: 48\n",
      "Most common targets: ['Brown Pelican', 'Snowy Egret', 'Redhead', 'Eurasian Collared-Dove']\n",
      "\n",
      "Top spot 10: (40.068893, -95.23534000000001)\n",
      "Number possible targets: 45\n",
      "Most common targets: ['Red-tailed Hawk', 'Bald Eagle', 'Song Sparrow', 'Merlin', 'Black-capped Chickadee']\n",
      "\n"
     ]
    }
   ],
   "source": [
    "main('MyEBirdData3.csv', 'lifelist.csv', month=2, day=14, num_spots=10, radius_miles = 50)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
